name: Get spot prices

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"

jobs:
  get_spot_prices:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: list timezones
      run: timedatectl list-timezones
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install deps
      run: pip install -r requirements.txt
    - name: Run a one-line script
      run: python scripts/get_spot_prices.py
    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Added new prices"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master